paddleWidth = 1
paddleHeight = 1
paddleHitboxX = 10
paddleHitboxY = 50
initialSpeed = 1.5
ballRadius = 8
screenWidth, screenHeight = love.graphics.getDimensions()
playerSpawnX = 25
playerSpawnY = screenHeight/2-25
cpuSpawnX = screenWidth-35
cpuSpawnY = screenHeight/2-25
playerScorePos = -45
cpuScorePos = 20